#' <%=ifelse(exists("plans") && plans, "@param plans A `redist_plans` object or plans_matrix where each row indicates a district assignment and each column is a plan.", "") %>
#' <%=ifelse(exists("shp") && shp, "@param shp A `redist_map` object, tibble, or data frame containing other columns.", "") %>
#' <%=ifelse(exists("group_pop") && group_pop, "@param group_pop Unqouted name of column in `shp` with group population.", "") %>
#' <%=ifelse(exists("total_pop") && total_pop, "@param total_pop Unqouted name of column in `shp` with total population.", "") %>
#' <%=ifelse(exists("epsg") && epsg, "@param epsg Numeric EPSG code to use to project the shapefile, if needed. Default is 3857.", "") %>
#' <%=ifelse(exists("ncores") && ncores, "@param ncores Integer number of cores to use. Default is 1.", "") %>
#' <%=ifelse(exists("adj") && adj, "@param adj Zero-indexed adjacency list. Not required if a `redist_map` is supplied for `shp`.", "") %>
#' <%=ifelse(exists("rvote") && rvote, "@param rvote Unqouted name of column in `shp` with group population.", "") %>
#' <%=ifelse(exists("dvote") && dvote, "@param dvote Unqouted name of column in `shp` with total population.", "") %>
#' <%=ifelse(exists("admin") && admin, "@param admin Unqouted name of column in `shp` with numeric identifiers for administrative units.", "") %>
#' <%=ifelse(exists("sub_admin") && sub_admin, "@param sub_admin Unqouted name of column in shp with numeric identifiers for subsidiary administrative units.", "") %>
#' <%=ifelse(exists("inc") && inc, "@param inc Unqouted name of logical column in `shp` indicating where incumbents live.", "") %>
