# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

polsbypopper <- function(from, to, area, perimeter, dm, nd) {
    .Call(`_redistmetrics_polsbypopper`, from, to, area, perimeter, dm, nd)
}

schwartzberg <- function(from, to, area, perimeter, dm, nd) {
    .Call(`_redistmetrics_schwartzberg`, from, to, area, perimeter, dm, nd)
}

talisman <- function(dvs, nd, alpha = 1, beta = 1) {
    .Call(`_redistmetrics_talisman`, dvs, nd, alpha, beta)
}

contiguity <- function(adj, group) {
    .Call(`_redistmetrics_contiguity`, adj, group)
}

hamming <- function(v, m) {
    .Call(`_redistmetrics_hamming`, v, m)
}

minkowski <- function(v, m, p) {
    .Call(`_redistmetrics_minkowski`, v, m, p)
}

log_st_map <- function(g, districts, counties, n_distr) {
    .Call(`_redistmetrics_log_st_map`, g, districts, counties, n_distr)
}

n_removed <- function(g, districts, n_distr) {
    .Call(`_redistmetrics_n_removed`, g, districts, n_distr)
}

agg_p2d <- function(dm, vote, nd) {
    .Call(`_redistmetrics_agg_p2d`, dm, vote, nd)
}

dseats <- function(dm, dcounts, rcounts, nd) {
    .Call(`_redistmetrics_dseats`, dm, dcounts, rcounts, nd)
}

dseatsDVS <- function(dvs) {
    .Call(`_redistmetrics_dseatsDVS`, dvs)
}

DVS <- function(dcounts, rcounts) {
    .Call(`_redistmetrics_DVS`, dcounts, rcounts)
}

effgapEP <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_effgapEP`, dvs, dseat_vec, nd)
}

effgap <- function(dcounts, rcounts, totvote) {
    .Call(`_redistmetrics_effgap`, dcounts, rcounts, totvote)
}

taugap <- function(tau, dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_taugap`, tau, dvs, dseat_vec, nd)
}

meanmedian <- function(dvs) {
    .Call(`_redistmetrics_meanmedian`, dvs)
}

bias <- function(dvs, nd) {
    .Call(`_redistmetrics_bias`, dvs, nd)
}

declination_simple <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_declination_simple`, dvs, dseat_vec, nd)
}

declination_angle <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_declination_angle`, dvs, dseat_vec, nd)
}

lopsidedwins <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_lopsidedwins`, dvs, dseat_vec, nd)
}

responsiveness <- function(dvs, v, nd, bandwidth = .01) {
    .Call(`_redistmetrics_responsiveness`, dvs, v, nd, bandwidth)
}

biasatv <- function(dvs, v, nd) {
    .Call(`_redistmetrics_biasatv`, dvs, v, nd)
}

RankedMarginalDev <- function(dvs) {
    .Call(`_redistmetrics_RankedMarginalDev`, dvs)
}

smoothseat <- function(dvs, nd) {
    .Call(`_redistmetrics_smoothseat`, dvs, nd)
}

segregationcalc <- function(distmat, grouppop, fullpop) {
    .Call(`_redistmetrics_segregationcalc`, distmat, grouppop, fullpop)
}

splits <- function(dm, community, nd, max_split) {
    .Call(`_redistmetrics_splits`, dm, community, nd, max_split)
}

distr_cty_splits <- function(dm, community, nd) {
    .Call(`_redistmetrics_distr_cty_splits`, dm, community, nd)
}

admin_splits_count <- function(dm, admin) {
    .Call(`_redistmetrics_admin_splits_count`, dm, admin)
}

var_info_mat <- function(m, i, pop) {
    .Call(`_redistmetrics_var_info_mat`, m, i, pop)
}

var_info_vec <- function(m, ref, pop) {
    .Call(`_redistmetrics_var_info_vec`, m, ref, pop)
}

