# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

phasecommute <- function(plans, current, pop, schools_idx_in, commute_times, ndists) {
    .Call(`_redistmetrics_phasecommute`, plans, current, pop, schools_idx_in, commute_times, ndists)
}

polsbypopper <- function(from, to, area, perimeter, dm, nd) {
    .Call(`_redistmetrics_polsbypopper`, from, to, area, perimeter, dm, nd)
}

schwartzberg <- function(from, to, area, perimeter, dm, nd) {
    .Call(`_redistmetrics_schwartzberg`, from, to, area, perimeter, dm, nd)
}

talisman <- function(dvs, nd, alpha = 1, beta = 1) {
    .Call(`_redistmetrics_talisman`, dvs, nd, alpha, beta)
}

contiguity <- function(adj, group) {
    .Call(`_redistmetrics_contiguity`, adj, group)
}

hamming <- function(v, m) {
    .Call(`_redistmetrics_hamming`, v, m)
}

minkowski <- function(v, m, p) {
    .Call(`_redistmetrics_minkowski`, v, m, p)
}

log_st_map <- function(g, districts, counties, n_distr) {
    .Call(`_redistmetrics_log_st_map`, g, districts, counties, n_distr)
}

n_removed <- function(g, districts, n_distr) {
    .Call(`_redistmetrics_n_removed`, g, districts, n_distr)
}

agg_p2d <- function(dm, vote, nd) {
    .Call(`_redistmetrics_agg_p2d`, dm, vote, nd)
}

dseats <- function(dcounts, rcounts) {
    .Call(`_redistmetrics_dseats`, dcounts, rcounts)
}

dseatsDVS <- function(dvs) {
    .Call(`_redistmetrics_dseatsDVS`, dvs)
}

DVS <- function(dcounts, rcounts) {
    .Call(`_redistmetrics_DVS`, dcounts, rcounts)
}

effgapEP <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_effgapEP`, dvs, dseat_vec, nd)
}

effgap <- function(dcounts, rcounts, totvote) {
    .Call(`_redistmetrics_effgap`, dcounts, rcounts, totvote)
}

taugap <- function(tau, dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_taugap`, tau, dvs, dseat_vec, nd)
}

meanmedian <- function(dvs) {
    .Call(`_redistmetrics_meanmedian`, dvs)
}

declination_simple <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_declination_simple`, dvs, dseat_vec, nd)
}

declination_angle <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_declination_angle`, dvs, dseat_vec, nd)
}

lopsidedwins <- function(dvs, dseat_vec, nd) {
    .Call(`_redistmetrics_lopsidedwins`, dvs, dseat_vec, nd)
}

responsiveness <- function(dvs, v, nd, bandwidth = .01) {
    .Call(`_redistmetrics_responsiveness`, dvs, v, nd, bandwidth)
}

biasatv <- function(dvs, v, nd) {
    .Call(`_redistmetrics_biasatv`, dvs, v, nd)
}

RankedMarginalDev <- function(dvs) {
    .Call(`_redistmetrics_RankedMarginalDev`, dvs)
}

smoothseat <- function(dvs, nd) {
    .Call(`_redistmetrics_smoothseat`, dvs, nd)
}

k_nearest_vote_sums <- function(distmat, totpop, target, rvote, dvote) {
    .Call(`_redistmetrics_k_nearest_vote_sums`, distmat, totpop, target, rvote, dvote)
}

reindex <- function(dm, nd) {
    .Call(`_redistmetrics_reindex`, dm, nd)
}

segregationcalc <- function(distmat, grouppop, fullpop) {
    .Call(`_redistmetrics_segregationcalc`, distmat, grouppop, fullpop)
}

splits <- function(dm, community, nd, max_split, skip_last = FALSE) {
    .Call(`_redistmetrics_splits`, dm, community, nd, max_split, skip_last)
}

distr_cty_splits <- function(dm, community, nd) {
    .Call(`_redistmetrics_distr_cty_splits`, dm, community, nd)
}

admin_splits_count <- function(dm, admin, nd, nc) {
    .Call(`_redistmetrics_admin_splits_count`, dm, admin, nd, nc)
}

tally_var <- function(dm, var, nd) {
    .Call(`_redistmetrics_tally_var`, dm, var, nd)
}

var_info_mat <- function(m, pop, ndists, ncores) {
    .Call(`_redistmetrics_var_info_mat`, m, pop, ndists, ncores)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_redistmetrics_RcppExport_registerCCallable`)
})
